export interface IndianState {
  name: string;
  code: string;
  cities: string[];
}

export const indianStates: IndianState[] = [
  {
    name: "Andhra Pradesh",
    code: "AP",
    cities: [
      "Visakhapatnam",
      "Vijayawada",
      "Guntur",
      "Nellore",
      "Kurnool",
      "Kadapa",
      "Anantapur",
      "Tirupati",
      "Kakinada",
      "Rajahmundry",
    ],
  },
  {
    name: "Arunachal Pradesh",
    code: "AR",
    cities: [
      "Itanagar",
      "Naharlagun",
      "Pasighat",
      "Bomdila",
      "Tawang",
      "Ziro",
      "Along",
      "Tezu",
      "Roing",
      "Daporijo",
    ],
  },
  {
    name: "Assam",
    code: "AS",
    cities: [
      "Guwahati",
      "Silchar",
      "Dibrugarh",
      "Jorhat",
      "Nagaon",
      "Tinsukia",
      "Tezpur",
      "Bongaigaon",
      "Dhubri",
      "Sivasagar",
    ],
  },
  {
    name: "Bihar",
    code: "BR",
    cities: [
      "Patna",
      "Gaya",
      "Bhagalpur",
      "Muzaffarpur",
      "Purnia",
      "Darbhanga",
      "Arrah",
      "Begusarai",
      "Katihar",
      "Chhapra",
    ],
  },
  {
    name: "Chhattisgarh",
    code: "CG",
    cities: [
      "Raipur",
      "Bhilai",
      "Korba",
      "Bilaspur",
      "Durg",
      "Rajnandgaon",
      "Jagdalpur",
      "Ambikapur",
      "Chirmiri",
      "Bhatapara",
    ],
  },
  {
    name: "Goa",
    code: "GA",
    cities: [
      "Panaji",
      "Margao",
      "Vasco da Gama",
      "Mapusa",
      "Ponda",
      "Bicholim",
      "Valpoi",
      "Sanquelim",
      "Curchorem",
      "Cuncolim",
    ],
  },
  {
    name: "Gujarat",
    code: "GJ",
    cities: [
      "Ahmedabad",
      "Surat",
      "Vadodara",
      "Rajkot",
      "Bhavnagar",
      "Jamnagar",
      "Gandhinagar",
      "Anand",
      "Bharuch",
      "Valsad",
    ],
  },
  {
    name: "Haryana",
    code: "HR",
    cities: [
      "Gurgaon",
      "Faridabad",
      "Panipat",
      "Yamunanagar",
      "Rohtak",
      "Hisar",
      "Karnal",
      "Sonipat",
      "Ambala",
      "Bhiwani",
    ],
  },
  {
    name: "Himachal Pradesh",
    code: "HP",
    cities: [
      "Shimla",
      "Mandi",
      "Solan",
      "Kullu",
      "Dharamshala",
      "Chamba",
      "Bilaspur",
      "Una",
      "Hamirpur",
      "Kangra",
    ],
  },
  {
    name: "Jharkhand",
    code: "JH",
    cities: [
      "Ranchi",
      "Jamshedpur",
      "Dhanbad",
      "Bokaro",
      "Deoghar",
      "Hazaribagh",
      "Giridih",
      "Ramgarh",
      "Medininagar",
      "Chatra",
    ],
  },
  {
    name: "Karnataka",
    code: "KA",
    cities: [
      "Bangalore",
      "Mysore",
      "Hubli",
      "Mangalore",
      "Belgaum",
      "Gulbarga",
      "Davangere",
      "Bellary",
      "Bijapur",
      "Shimoga",
    ],
  },
  {
    name: "Kerala",
    code: "KL",
    cities: [
      "Thiruvananthapuram",
      "Kochi",
      "Kozhikode",
      "Thrissur",
      "Kollam",
      "Alappuzha",
      "Palakkad",
      "Malappuram",
      "Kannur",
      "Kottayam",
    ],
  },
  {
    name: "Madhya Pradesh",
    code: "MP",
    cities: [
      "Bhopal",
      "Indore",
      "Jabalpur",
      "Gwalior",
      "Ujjain",
      "Sagar",
      "Dewas",
      "Satna",
      "Ratlam",
      "Rewa",
    ],
  },
  {
    name: "Maharashtra",
    code: "MH",
    cities: [
      "Mumbai",
      "Pune",
      "Nagpur",
      "Thane",
      "Nashik",
      "Aurangabad",
      "Solapur",
      "Kolhapur",
      "Amravati",
      "Nanded",
    ],
  },
  {
    name: "Manipur",
    code: "MN",
    cities: [
      "Imphal",
      "Thoubal",
      "Bishnupur",
      "Churachandpur",
      "Ukhrul",
      "Senapati",
      "Tamenglong",
      "Chandel",
      "Jiribam",
      "Kakching",
    ],
  },
  {
    name: "Meghalaya",
    code: "ML",
    cities: [
      "Shillong",
      "Tura",
      "Jowai",
      "Nongstoin",
      "Williamnagar",
      "Baghmara",
      "Nongpoh",
      "Mairang",
      "Resubelpara",
      "Khliehriat",
    ],
  },
  {
    name: "Mizoram",
    code: "MZ",
    cities: [
      "Aizawl",
      "Lunglei",
      "Saiha",
      "Champhai",
      "Kolasib",
      "Serchhip",
      "Lawngtlai",
      "Mamit",
      "Saitual",
      "Khawzawl",
    ],
  },
  {
    name: "Nagaland",
    code: "NL",
    cities: [
      "Kohima",
      "Dimapur",
      "Mokokchung",
      "Tuensang",
      "Wokha",
      "Zunheboto",
      "Phek",
      "Mon",
      "Kiphire",
      "Longleng",
    ],
  },
  {
    name: "Odisha",
    code: "OD",
    cities: [
      "Bhubaneswar",
      "Cuttack",
      "Rourkela",
      "Brahmapur",
      "Sambalpur",
      "Puri",
      "Baleshwar",
      "Baripada",
      "Bhadrak",
      "Balangir",
    ],
  },
  {
    name: "Punjab",
    code: "PB",
    cities: [
      "Ludhiana",
      "Amritsar",
      "Jalandhar",
      "Patiala",
      "Bathinda",
      "Pathankot",
      "Moga",
      "Hoshiarpur",
      "Batala",
      "Muktsar",
    ],
  },
  {
    name: "Rajasthan",
    code: "RJ",
    cities: [
      "Jaipur",
      "Jodhpur",
      "Kota",
      "Bikaner",
      "Ajmer",
      "Udaipur",
      "Bhilwara",
      "Alwar",
      "Sri Ganganagar",
      "Sikar",
    ],
  },
  {
    name: "Sikkim",
    code: "SK",
    cities: [
      "Gangtok",
      "Namchi",
      "Mangan",
      "Gyalshing",
      "Ravongla",
      "Lachung",
      "Pelling",
      "Yuksom",
      "Rangpo",
      "Singtam",
    ],
  },
  {
    name: "Tamil Nadu",
    code: "TN",
    cities: [
      "Chennai",
      "Coimbatore",
      "Madurai",
      "Salem",
      "Tiruchirappalli",
      "Vellore",
      "Erode",
      "Tiruppur",
      "Thoothukkudi",
      "Dindigul",
    ],
  },
  {
    name: "Telangana",
    code: "TS",
    cities: [
      "Hyderabad",
      "Warangal",
      "Nizamabad",
      "Karimnagar",
      "Ramagundam",
      "Khammam",
      "Mahbubnagar",
      "Nalgonda",
      "Adilabad",
      "Siddipet",
    ],
  },
  {
    name: "Tripura",
    code: "TR",
    cities: [
      "Agartala",
      "Udaipur",
      "Dharmanagar",
      "Kailasahar",
      "Belonia",
      "Khowai",
      "Teliamura",
      "Amarpur",
      "Sabroom",
      "Kamalpur",
    ],
  },
  {
    name: "Uttar Pradesh",
    code: "UP",
    cities: [
      "Lucknow",
      "Kanpur",
      "Ghaziabad",
      "Agra",
      "Varanasi",
      "Prayagraj",
      "Bareilly",
      "Aligarh",
      "Moradabad",
      "Saharanpur",
    ],
  },
  {
    name: "Uttarakhand",
    code: "UT",
    cities: [
      "Dehradun",
      "Haridwar",
      "Roorkee",
      "Haldwani",
      "Rudrapur",
      "Kashipur",
      "Rishikesh",
      "Kotdwara",
      "Ramnagar",
      "Pithoragarh",
    ],
  },
  {
    name: "West Bengal",
    code: "WB",
    cities: [
      "Kolkata",
      "Howrah",
      "Durgapur",
      "Asansol",
      "Siliguri",
      "Bardhaman",
      "Malda",
      "Baharampur",
      "Habra",
      "Kharagpur",
    ],
  },
  {
    name: "Delhi",
    code: "DL",
    cities: [
      "New Delhi",
      "North Delhi",
      "South Delhi",
      "East Delhi",
      "West Delhi",
      "Central Delhi",
      "Shahdara",
      "Dwarka",
      "Rohini",
      "Pitampura",
    ],
  },
  {
    name: "Jammu and Kashmir",
    code: "JK",
    cities: [
      "Srinagar",
      "Jammu",
      "Anantnag",
      "Baramulla",
      "Udhampur",
      "Kathua",
      "Rajouri",
      "Poonch",
      "Doda",
      "Kishtwar",
    ],
  },
  {
    name: "Ladakh",
    code: "LA",
    cities: [
      "Leh",
      "Kargil",
      "Drass",
      "Nubra Valley",
      "Zanskar",
      "Pangong Tso",
      "Tso Moriri",
      "Hemis",
      "Alchi",
      "Lamayuru",
    ],
  },
  {
    name: "Chandigarh",
    code: "CH",
    cities: ["Chandigarh", "Mohali", "Panchkula"],
  },
  {
    name: "Dadra and Nagar Haveli and Daman and Diu",
    code: "DN",
    cities: [
      "Silvassa",
      "Daman",
      "Diu",
      "Naroli",
      "Amli",
      "Kadaiya",
      "Khanvel",
      "Rakholi",
      "Samarvarni",
      "Dadra",
    ],
  },
  {
    name: "Lakshadweep",
    code: "LD",
    cities: [
      "Kavaratti",
      "Agatti",
      "Amini",
      "Andrott",
      "Kadmat",
      "Kalpeni",
      "Kiltan",
      "Minicoy",
      "Chetlat",
      "Bitra",
    ],
  },
  {
    name: "Puducherry",
    code: "PY",
    cities: [
      "Puducherry",
      "Karaikal",
      "Mahe",
      "Yanam",
      "Ozhukarai",
      "Villianur",
      "Bahour",
      "Nettapakkam",
      "Ariyankuppam",
      "Mannadipet",
    ],
  },
];

export const getCitiesByState = (stateName: string): string[] => {
  const state = indianStates.find((s) => s.name === stateName);
  return state ? state.cities : [];
};

export const getStateByCode = (code: string): IndianState | undefined => {
  return indianStates.find((s) => s.code === code);
};
