export interface IndianState {
  name: string;
  code: string;
  cities: string[];
}

// Comprehensive list of Indian states and cities, alphabetically sorted
export const indianStates: IndianState[] = [
  {
    name: "Andhra Pradesh",
    code: "AP",
    cities: [
      "Adoni",
      "Amaravati",
      "Anantapur",
      "Bapatla",
      "Bheemunipatnam",
      "Bhimavaram",
      "Bobbili",
      "Chilakaluripet",
      "Chirala",
      "Chittoor",
      "Dharmavaram",
      "Eluru",
      "Gudivada",
      "Gudur",
      "Guntakal",
      "Guntur",
      "Hindupur",
      "Jaggaiahpet",
      "Jammalamadugu",
      "Kadapa",
      "Kadiri",
      "Kakinada",
      "Kandukur",
      "Kavali",
      "Kovvur",
      "Kurnool",
      "Machilipatnam",
      "Madanapalle",
      "Mangalagiri",
      "Markapur",
      "Nagari",
      "Nandyal",
      "Narasapuram",
      "Narasaraopet",
      "Nellore",
      "Nidadavole",
      "Nuzvid",
      "Ongole",
      "Palacole",
      "Palasa Kasibugga",
      "Parvathipuram",
      "Pedana",
      "Peddapuram",
      "Pithapuram",
      "Ponnur",
      "Proddatur",
      "Punganur",
      "Puttur",
      "Rajahmundry",
      "Rajam",
      "Rajampet",
      "Ramachandrapuram",
      "Rayachoti",
      "Rayadurg",
      "Renigunta",
      "Repalle",
      "Salur",
      "Samalkot",
      "Sattenapalle",
      "Srikakulam",
      "Srikalahasti",
      "Srisailam",
      "Tadepalligudem",
      "Tadipatri",
      "Tenali",
      "Tirupati",
      "Tiruvuru",
      "Tuni",
      "Uravakonda",
      "Venkatagiri",
      "Vijayawada",
      "Vinukonda",
      "Visakhapatnam",
      "Vizianagaram",
      "Yemmiganur",
    ],
  },
  {
    name: "Arunachal Pradesh",
    code: "AR",
    cities: [
      "Along",
      "Anini",
      "Basar",
      "Bhalukpong",
      "Bomdila",
      "Changlang",
      "Daporijo",
      "Deomali",
      "Dirang",
      "Hayuliang",
      "Itanagar",
      "Jairampur",
      "Khonsa",
      "Koloriang",
      "Longding",
      "Miao",
      "Naharlagun",
      "Namsai",
      "Pasighat",
      "Roing",
      "Seppa",
      "Tawang",
      "Tezu",
      "Ziro",
    ],
  },
  {
    name: "Assam",
    code: "AS",
    cities: [
      "Barpeta",
      "Bongaigaon",
      "Dhubri",
      "Dibrugarh",
      "Diphu",
      "Goalpara",
      "Golaghat",
      "Guwahati",
      "Haflong",
      "Hailakandi",
      "Jorhat",
      "Karimganj",
      "Kokrajhar",
      "Lakhimpur",
      "Mangaldoi",
      "Morigaon",
      "Nagaon",
      "Nalbari",
      "North Lakhimpur",
      "Rangia",
      "Sibsagar",
      "Silchar",
      "Tezpur",
      "Tinsukia",
    ],
  },
  {
    name: "Bihar",
    code: "BR",
    cities: [
      "Araria",
      "Arrah",
      "Aurangabad",
      "Bagaha",
      "Barh",
      "Begusarai",
      "Bettiah",
      "Bhagalpur",
      "Bihar Sharif",
      "Buxar",
      "Chhapra",
      "Darbhanga",
      "Dehri",
      "Dinapur Nizamat",
      "Gaya",
      "Hajipur",
      "Jamalpur",
      "Jamui",
      "Jehanabad",
      "Katihar",
      "Khagaria",
      "Kishanganj",
      "Lakhisarai",
      "Madhepura",
      "Madhubani",
      "Motihari",
      "Munger",
      "Muzaffarpur",
      "Nalanda",
      "Nawada",
      "Patna",
      "Purnia",
      "Pusa",
      "Raxaul",
      "Saharsa",
      "Samastipur",
      "Sasaram",
      "Sheikhpura",
      "Sheohar",
      "Sitamarhi",
      "Siwan",
      "Supaul",
      "Warisaliganj",
    ],
  },
  {
    name: "Chandigarh",
    code: "CH",
    cities: ["Chandigarh", "Mohali", "Panchkula"],
  },
  {
    name: "Chhattisgarh",
    code: "CG",
    cities: [
      "Ambikapur",
      "Bhilai",
      "Bilaspur",
      "Chirmiri",
      "Dhamtari",
      "Durg",
      "Jagdalpur",
      "Korba",
      "Mahasamund",
      "Raigarh",
      "Raipur",
      "Rajnandgaon",
      "Rourkela",
      "Surguja",
    ],
  },
  {
    name: "Dadra and Nagar Haveli and Daman and Diu",
    code: "DN",
    cities: [
      "Amli",
      "Dadra",
      "Daman",
      "Diu",
      "Kadaiya",
      "Khanvel",
      "Naroli",
      "Rakholi",
      "Samarvarni",
      "Silvassa",
    ],
  },
  {
    name: "Delhi",
    code: "DL",
    cities: [
      "Central Delhi",
      "East Delhi",
      "New Delhi",
      "North Delhi",
      "North East Delhi",
      "North West Delhi",
      "Shahdara",
      "South Delhi",
      "South East Delhi",
      "South West Delhi",
      "West Delhi",
      "Dwarka",
      "Pitampura",
      "Rohini",
    ],
  },
  {
    name: "Goa",
    code: "GA",
    cities: [
      "Bicholim",
      "Cuncolim",
      "Curchorem",
      "Mapusa",
      "Margao",
      "Panaji",
      "Ponda",
      "Sanquelim",
      "Valpoi",
      "Vasco da Gama",
    ],
  },
  {
    name: "Gujarat",
    code: "GJ",
    cities: [
      "Ahmedabad",
      "Amreli",
      "Anand",
      "Bharuch",
      "Bhavnagar",
      "Bhuj",
      "Botad",
      "Chhota Udaipur",
      "Dahod",
      "Gandhidham",
      "Gandhinagar",
      "Godhra",
      "Himatnagar",
      "Jamnagar",
      "Junagadh",
      "Kheda",
      "Mahesana",
      "Modasa",
      "Morbi",
      "Nadiad",
      "Navsari",
      "Palanpur",
      "Patan",
      "Porbandar",
      "Rajkot",
      "Surat",
      "Surendranagar",
      "Vadodara",
      "Valsad",
      "Veraval",
    ],
  },
  {
    name: "Haryana",
    code: "HR",
    cities: [
      "Ambala",
      "Bahadurgarh",
      "Bhiwani",
      "Charkhi Dadri",
      "Faridabad",
      "Fatehabad",
      "Gurgaon",
      "Hisar",
      "Jhajjar",
      "Jind",
      "Kaithal",
      "Karnal",
      "Kurukshetra",
      "Mahendragarh",
      "Narnaul",
      "Narwana",
      "Palwal",
      "Panipat",
      "Pehowa",
      "Rewari",
      "Rohtak",
      "Sirsa",
      "Sonipat",
      "Thanesar",
      "Tohana",
      "Yamunanagar",
    ],
  },
  {
    name: "Himachal Pradesh",
    code: "HP",
    cities: [
      "Baddi",
      "Bilaspur",
      "Chamba",
      "Dalhousie",
      "Dharamshala",
      "Hamirpur",
      "Kangra",
      "Kullu",
      "Mandi",
      "Manali",
      "Nahan",
      "Palampur",
      "Shimla",
      "Solan",
      "Una",
    ],
  },
  {
    name: "Jammu and Kashmir",
    code: "JK",
    cities: [
      "Anantnag",
      "Baramulla",
      "Doda",
      "Gulmarg",
      "Jammu",
      "Kathua",
      "Kishtwar",
      "Kupwara",
      "Leh",
      "Poonch",
      "Pulwama",
      "Rajouri",
      "Srinagar",
      "Udhampur",
    ],
  },
  {
    name: "Jharkhand",
    code: "JH",
    cities: [
      "Bokaro",
      "Chaibasa",
      "Chatra",
      "Deoghar",
      "Dhanbad",
      "Dumka",
      "Garhwa",
      "Giridih",
      "Godda",
      "Gumla",
      "Hazaribagh",
      "Jamshedpur",
      "Jamtara",
      "Khunti",
      "Latehar",
      "Lohardaga",
      "Medininagar",
      "Pakur",
      "Ramgarh",
      "Ranchi",
      "Sahebganj",
      "Simdega",
    ],
  },
  {
    name: "Karnataka",
    code: "KA",
    cities: [
      "Bagalkot",
      "Ballari",
      "Bangalore",
      "Belagavi",
      "Bellary",
      "Bengaluru",
      "Bhadravati",
      "Bidar",
      "Bijapur",
      "Chikmagalur",
      "Chitradurga",
      "Davangere",
      "Dharwad",
      "Gadag",
      "Gulbarga",
      "Hassan",
      "Haveri",
      "Hubli",
      "Kolar",
      "Koppal",
      "Mandya",
      "Mangalore",
      "Mysore",
      "Raichur",
      "Shimoga",
      "Tumkur",
      "Udupi",
      "Vijayapura",
    ],
  },
  {
    name: "Kerala",
    code: "KL",
    cities: [
      "Alappuzha",
      "Aluva",
      "Attingal",
      "Chalakudy",
      "Changanassery",
      "Ernakulam",
      "Guruvayur",
      "Kannur",
      "Kasaragod",
      "Kochi",
      "Kollam",
      "Kottayam",
      "Kozhikode",
      "Malappuram",
      "Manjeri",
      "Neyyattinkara",
      "Palakkad",
      "Ponnani",
      "Thalassery",
      "Thiruvananthapuram",
      "Thrissur",
      "Tirur",
    ],
  },
  {
    name: "Ladakh",
    code: "LA",
    cities: [
      "Alchi",
      "Drass",
      "Hemis",
      "Kargil",
      "Lamayuru",
      "Leh",
      "Nubra Valley",
      "Pangong Tso",
      "Tso Moriri",
      "Zanskar",
    ],
  },
  {
    name: "Lakshadweep",
    code: "LD",
    cities: [
      "Agatti",
      "Amini",
      "Andrott",
      "Bitra",
      "Chetlat",
      "Kadmat",
      "Kalpeni",
      "Kavaratti",
      "Kiltan",
      "Minicoy",
    ],
  },
  {
    name: "Madhya Pradesh",
    code: "MP",
    cities: [
      "Balaghat",
      "Barwani",
      "Betul",
      "Bhind",
      "Bhopal",
      "Burhanpur",
      "Chhatarpur",
      "Chhindwara",
      "Damoh",
      "Datia",
      "Dewas",
      "Dhar",
      "Guna",
      "Gwalior",
      "Harda",
      "Hoshangabad",
      "Indore",
      "Itarsi",
      "Jabalpur",
      "Khandwa",
      "Khargone",
      "Mandsaur",
      "Morena",
      "Murwara",
      "Nagda",
      "Neemuch",
      "Pithampur",
      "Ratlam",
      "Rewa",
      "Sagar",
      "Satna",
      "Sehore",
      "Seoni",
      "Shahdol",
      "Shajapur",
      "Sheopur",
      "Shivpuri",
      "Sidhi",
      "Singrauli",
      "Tikamgarh",
      "Ujjain",
      "Vidisha",
    ],
  },
  {
    name: "Maharashtra",
    code: "MH",
    cities: [
      "Ahmednagar",
      "Akola",
      "Amravati",
      "Aurangabad",
      "Beed",
      "Bhandara",
      "Bhiwandi",
      "Bhusawal",
      "Chandrapur",
      "Dhule",
      "Gondia",
      "Ichalkaranji",
      "Jalgaon",
      "Jalna",
      "Kolhapur",
      "Latur",
      "Malegaon",
      "Mira-Bhayandar",
      "Mumbai",
      "Nagpur",
      "Nanded",
      "Nashik",
      "Navi Mumbai",
      "Osmanabad",
      "Palghar",
      "Parbhani",
      "Pimpri-Chinchwad",
      "Pune",
      "Raigad",
      "Ratnagiri",
      "Sangli",
      "Satara",
      "Solapur",
      "Thane",
      "Ulhasnagar",
      "Vasai-Virar",
      "Wardha",
      "Washim",
      "Yavatmal",
    ],
  },
  {
    name: "Manipur",
    code: "MN",
    cities: [
      "Bishnupur",
      "Chandel",
      "Churachandpur",
      "Imphal",
      "Jiribam",
      "Kakching",
      "Kamjong",
      "Kangpokpi",
      "Noney",
      "Pherzawl",
      "Senapati",
      "Tamenglong",
      "Tengnoupal",
      "Thoubal",
      "Ukhrul",
    ],
  },
  {
    name: "Meghalaya",
    code: "ML",
    cities: [
      "Baghmara",
      "Cherrapunji",
      "Jowai",
      "Khliehriat",
      "Mairang",
      "Nongpoh",
      "Nongstoin",
      "Resubelpara",
      "Shillong",
      "Tura",
      "Williamnagar",
    ],
  },
  {
    name: "Mizoram",
    code: "MZ",
    cities: [
      "Aizawl",
      "Champhai",
      "Khawzawl",
      "Kolasib",
      "Lawngtlai",
      "Lunglei",
      "Mamit",
      "Saiha",
      "Saitual",
      "Serchhip",
    ],
  },
  {
    name: "Nagaland",
    code: "NL",
    cities: [
      "Dimapur",
      "Kiphire",
      "Kohima",
      "Longleng",
      "Mokokchung",
      "Mon",
      "Phek",
      "Tuensang",
      "Wokha",
      "Zunheboto",
    ],
  },
  {
    name: "Odisha",
    code: "OD",
    cities: [
      "Angul",
      "Balangir",
      "Baleshwar",
      "Baripada",
      "Bhadrak",
      "Bhawanipatna",
      "Bhubaneswar",
      "Brahmapur",
      "Cuttack",
      "Dhenkanal",
      "Jagatsinghpur",
      "Jajpur",
      "Jharsuguda",
      "Kendrapara",
      "Kendujhar",
      "Koraput",
      "Malkangiri",
      "Nabarangpur",
      "Nayagarh",
      "Nuapada",
      "Puri",
      "Rayagada",
      "Rourkela",
      "Sambalpur",
      "Subarnapur",
      "Sundargarh",
    ],
  },
  {
    name: "Puducherry",
    code: "PY",
    cities: [
      "Ariyankuppam",
      "Bahour",
      "Karaikal",
      "Mahe",
      "Mannadipet",
      "Nettapakkam",
      "Ozhukarai",
      "Puducherry",
      "Villianur",
      "Yanam",
    ],
  },
  {
    name: "Punjab",
    code: "PB",
    cities: [
      "Abohar",
      "Amritsar",
      "Barnala",
      "Batala",
      "Bathinda",
      "Fazilka",
      "Firozpur",
      "Gurdaspur",
      "Hoshiarpur",
      "Jalandhar",
      "Kapurthala",
      "Khanna",
      "Ludhiana",
      "Mansa",
      "Moga",
      "Mohali",
      "Muktsar",
      "Mullanpur",
      "Nabha",
      "Pathankot",
      "Patiala",
      "Phagwara",
      "Rajpura",
      "Sangrur",
      "Sunam",
      "Tarn Taran",
    ],
  },
  {
    name: "Rajasthan",
    code: "RJ",
    cities: [
      "Ajmer",
      "Alwar",
      "Banswara",
      "Baran",
      "Barmer",
      "Beawar",
      "Bharatpur",
      "Bhilwara",
      "Bikaner",
      "Bundi",
      "Chittaurgarh",
      "Churu",
      "Dausa",
      "Deeg",
      "Dholpur",
      "Dungarpur",
      "Ganganagar",
      "Gangapur",
      "Hanumangarh",
      "Jaipur",
      "Jaisalmer",
      "Jalore",
      "Jhalawar",
      "Jhunjhunu",
      "Jodhpur",
      "Karauli",
      "Kota",
      "Kumbhalgarh",
      "Nagaur",
      "Nathdwara",
      "Pali",
      "Phalodi",
      "Pratapgarh",
      "Rajsamand",
      "Sawai Madhopur",
      "Sikar",
      "Sirohi",
      "Tonk",
      "Udaipur",
    ],
  },
  {
    name: "Sikkim",
    code: "SK",
    cities: [
      "Gangtok",
      "Gyalshing",
      "Lachung",
      "Mangan",
      "Namchi",
      "Pelling",
      "Rangpo",
      "Ravongla",
      "Singtam",
      "Yuksom",
    ],
  },
  {
    name: "Tamil Nadu",
    code: "TN",
    cities: [
      "Arakkonam",
      "Arani",
      "Arcot",
      "Aruppukkottai",
      "Bhavani",
      "Chennai",
      "Cheyyar",
      "Coimbatore",
      "Cuddalore",
      "Dharmapuri",
      "Dindigul",
      "Erode",
      "Gobichettipalayam",
      "Gudiyatham",
      "Hosur",
      "Kanchipuram",
      "Karaikudi",
      "Karur",
      "Kovilpatti",
      "Krishnagiri",
      "Kumbakonam",
      "Madurai",
      "Manapparai",
      "Mayiladuthurai",
      "Mettupalayam",
      "Nagapattinam",
      "Nagercoil",
      "Namakkal",
      "Neyveli",
      "Nilgiris",
      "Ooty",
      "Palani",
      "Palladam",
      "Pallavaram",
      "Pallikondai",
      "Panruti",
      "Paramakudi",
      "Pattukkottai",
      "Pollachi",
      "Pudukkottai",
      "Rajapalayam",
      "Ramanathapuram",
      "Salem",
      "Sivaganga",
      "Sivakasi",
      "Sriperumbudur",
      "Tenkasi",
      "Thanjavur",
      "Theni",
      "Thoothukkudi",
      "Tindivanam",
      "Tiruchirappalli",
      "Tirunelveli",
      "Tiruppur",
      "Tiruvannamalai",
      "Tiruvarur",
      "Tuticorin",
      "Udagamandalam",
      "Vellore",
      "Villupuram",
      "Virudhunagar",
    ],
  },
  {
    name: "Telangana",
    code: "TS",
    cities: [
      "Adilabad",
      "Bhadrachalam",
      "Bhongir",
      "Bodhan",
      "Hyderabad",
      "Jagtial",
      "Jangaon",
      "Jayashankar Bhupalpally",
      "Jogulamba Gadwal",
      "Kamareddy",
      "Karimnagar",
      "Khammam",
      "Kumuram Bheem",
      "Mahabubabad",
      "Mahabubnagar",
      "Mancherial",
      "Medak",
      "Medchal–Malkajgiri",
      "Mulugu",
      "Nagarkurnool",
      "Nalgonda",
      "Narayanpet",
      "Nirmal",
      "Nizamabad",
      "Peddapalli",
      "Rajanna Sircilla",
      "Rangareddy",
      "Sangareddy",
      "Siddipet",
      "Suryapet",
      "Vikarabad",
      "Wanaparthy",
      "Warangal Rural",
      "Warangal Urban",
      "Yadadri Bhuvanagiri",
    ],
  },
  {
    name: "Tripura",
    code: "TR",
    cities: [
      "Agartala",
      "Amarpur",
      "Belonia",
      "Dharmanagar",
      "Kailasahar",
      "Kamalpur",
      "Khowai",
      "Sabroom",
      "Teliamura",
      "Udaipur",
    ],
  },
  {
    name: "Uttar Pradesh",
    code: "UP",
    cities: [
      "Agra",
      "Aligarh",
      "Ambedkar Nagar",
      "Amethi",
      "Amroha",
      "Auraiya",
      "Azamgarh",
      "Baghpat",
      "Bahraich",
      "Ballia",
      "Balrampur",
      "Banda",
      "Barabanki",
      "Bareilly",
      "Basti",
      "Bhadohi",
      "Bijnor",
      "Budaun",
      "Bulandshahr",
      "Chandauli",
      "Chitrakoot",
      "Deoria",
      "Etah",
      "Etawah",
      "Farrukhabad",
      "Fatehpur",
      "Firozabad",
      "Gautam Buddha Nagar",
      "Ghaziabad",
      "Ghazipur",
      "Gonda",
      "Gorakhpur",
      "Hamirpur",
      "Hapur",
      "Hardoi",
      "Hathras",
      "Jalaun",
      "Jaunpur",
      "Jhansi",
      "Kannauj",
      "Kanpur Dehat",
      "Kanpur Nagar",
      "Kasganj",
      "Kaushambi",
      "Kushinagar",
      "Lakhimpur Kheri",
      "Lalitpur",
      "Lucknow",
      "Maharajganj",
      "Mahoba",
      "Mainpuri",
      "Mathura",
      "Mau",
      "Meerut",
      "Mirzapur",
      "Moradabad",
      "Muzaffarnagar",
      "Pilibhit",
      "Pratapgarh",
      "Prayagraj",
      "Raebareli",
      "Rampur",
      "Saharanpur",
      "Sambhal",
      "Sant Kabir Nagar",
      "Shahjahanpur",
      "Shamli",
      "Shravasti",
      "Siddharthnagar",
      "Sitapur",
      "Sonbhadra",
      "Sultanpur",
      "Unnao",
      "Varanasi",
    ],
  },
  {
    name: "Uttarakhand",
    code: "UT",
    cities: [
      "Almora",
      "Bageshwar",
      "Chamoli",
      "Champawat",
      "Dehradun",
      "Haridwar",
      "Nainital",
      "Pauri Garhwal",
      "Pithoragarh",
      "Rudraprayag",
      "Tehri Garhwal",
      "Udham Singh Nagar",
      "Uttarkashi",
    ],
  },
  {
    name: "West Bengal",
    code: "WB",
    cities: [
      "Alipurduar",
      "Bankura",
      "Bardhaman",
      "Birbhum",
      "Cooch Behar",
      "Dakshin Dinajpur",
      "Darjeeling",
      "Hooghly",
      "Howrah",
      "Jalpaiguri",
      "Jhargram",
      "Kalimpong",
      "Kolkata",
      "Malda",
      "Murshidabad",
      "Nadia",
      "North 24 Parganas",
      "Paschim Bardhaman",
      "Paschim Medinipur",
      "Purba Bardhaman",
      "Purba Medinipur",
      "Purulia",
      "South 24 Parganas",
      "Uttar Dinajpur",
    ],
  },
];

// Helper function to get cities by state name
export const getCitiesByState = (stateName: string): string[] => {
  const state = indianStates.find((s) => s.name === stateName);
  return state ? state.cities.sort() : [];
};

// Helper function to get state by code
export const getStateByCode = (code: string): IndianState | undefined => {
  return indianStates.find((s) => s.code === code);
};

// Helper function to get all states sorted alphabetically
export const getSortedStates = (): IndianState[] => {
  return [...indianStates].sort((a, b) => a.name.localeCompare(b.name));
};

// Helper function to search cities by partial name
export const searchCitiesByState = (
  stateName: string,
  searchTerm: string
): string[] => {
  const cities = getCitiesByState(stateName);
  if (!searchTerm) return cities;
  return cities.filter((city) =>
    city.toLowerCase().includes(searchTerm.toLowerCase())
  );
};
