export interface Country {
  name: string;
  code: string;
  dialCode: string;
}

export const countries: Country[] = [
  { name: "India", code: "IN", dialCode: "+91" },
  { name: "United States", code: "US", dialCode: "+1" },
  { name: "United Kingdom", code: "GB", dialCode: "+44" },
  { name: "Canada", code: "CA", dialCode: "+1" },
  { name: "Australia", code: "AU", dialCode: "+61" },
  { name: "Germany", code: "DE", dialCode: "+49" },
  { name: "France", code: "FR", dialCode: "+33" },
  { name: "Japan", code: "JP", dialCode: "+81" },
  { name: "China", code: "CN", dialCode: "+86" },
  { name: "Singapore", code: "SG", dialCode: "+65" },
  { name: "United Arab Emirates", code: "AE", dialCode: "+971" },
  { name: "Saudi Arabia", code: "SA", dialCode: "+966" },
  { name: "South Africa", code: "ZA", dialCode: "+27" },
  { name: "Brazil", code: "BR", dialCode: "+55" },
  { name: "Mexico", code: "MX", dialCode: "+52" },
  { name: "Russia", code: "RU", dialCode: "+7" },
  { name: "South Korea", code: "KR", dialCode: "+82" },
  { name: "Italy", code: "IT", dialCode: "+39" },
  { name: "Spain", code: "ES", dialCode: "+34" },
  { name: "Netherlands", code: "NL", dialCode: "+31" },
  { name: "Switzerland", code: "CH", dialCode: "+41" },
  { name: "Sweden", code: "SE", dialCode: "+46" },
  { name: "Norway", code: "NO", dialCode: "+47" },
  { name: "Denmark", code: "DK", dialCode: "+45" },
  { name: "Finland", code: "FI", dialCode: "+358" },
  { name: "Belgium", code: "BE", dialCode: "+32" },
  { name: "Austria", code: "AT", dialCode: "+43" },
  { name: "Portugal", code: "PT", dialCode: "+351" },
  { name: "Greece", code: "GR", dialCode: "+30" },
  { name: "Poland", code: "PL", dialCode: "+48" },
  { name: "Turkey", code: "TR", dialCode: "+90" },
  { name: "Israel", code: "IL", dialCode: "+972" },
  { name: "Egypt", code: "EG", dialCode: "+20" },
  { name: "Nigeria", code: "NG", dialCode: "+234" },
  { name: "Kenya", code: "KE", dialCode: "+254" },
  { name: "Thailand", code: "TH", dialCode: "+66" },
  { name: "Vietnam", code: "VN", dialCode: "+84" },
  { name: "Indonesia", code: "ID", dialCode: "+62" },
  { name: "Malaysia", code: "MY", dialCode: "+60" },
  { name: "Philippines", code: "PH", dialCode: "+63" },
  { name: "New Zealand", code: "NZ", dialCode: "+64" },
  { name: "Pakistan", code: "PK", dialCode: "+92" },
  { name: "Bangladesh", code: "BD", dialCode: "+880" },
  { name: "Sri Lanka", code: "LK", dialCode: "+94" },
  { name: "Nepal", code: "NP", dialCode: "+977" },
  { name: "Bhutan", code: "BT", dialCode: "+975" },
  { name: "Maldives", code: "MV", dialCode: "+960" },
  { name: "Afghanistan", code: "AF", dialCode: "+93" },
  { name: "Iran", code: "IR", dialCode: "+98" },
  { name: "Iraq", code: "IQ", dialCode: "+964" },
  { name: "Kuwait", code: "KW", dialCode: "+965" },
  { name: "Qatar", code: "QA", dialCode: "+974" },
  { name: "Oman", code: "OM", dialCode: "+968" },
  { name: "Bahrain", code: "BH", dialCode: "+973" },
  { name: "Jordan", code: "JO", dialCode: "+962" },
  { name: "Lebanon", code: "LB", dialCode: "+961" },
  { name: "Syria", code: "SY", dialCode: "+963" },
  { name: "Yemen", code: "YE", dialCode: "+967" },
  { name: "Morocco", code: "MA", dialCode: "+212" },
  { name: "Algeria", code: "DZ", dialCode: "+213" },
  { name: "Tunisia", code: "TN", dialCode: "+216" },
  { name: "Libya", code: "LY", dialCode: "+218" },
  { name: "Sudan", code: "SD", dialCode: "+249" },
  { name: "Ethiopia", code: "ET", dialCode: "+251" },
  { name: "Tanzania", code: "TZ", dialCode: "+255" },
  { name: "Uganda", code: "UG", dialCode: "+256" },
  { name: "Ghana", code: "GH", dialCode: "+233" },
  { name: "Senegal", code: "SN", dialCode: "+221" },
  { name: "Ivory Coast", code: "CI", dialCode: "+225" },
  { name: "Cameroon", code: "CM", dialCode: "+237" },
  { name: "Angola", code: "AO", dialCode: "+244" },
  { name: "Mozambique", code: "MZ", dialCode: "+258" },
  { name: "Zimbabwe", code: "ZW", dialCode: "+263" },
  { name: "Zambia", code: "ZM", dialCode: "+260" },
  { name: "Malawi", code: "MW", dialCode: "+265" },
  { name: "Botswana", code: "BW", dialCode: "+267" },
  { name: "Namibia", code: "NA", dialCode: "+264" },
  { name: "Lesotho", code: "LS", dialCode: "+266" },
  { name: "Eswatini", code: "SZ", dialCode: "+268" },
  { name: "Madagascar", code: "MG", dialCode: "+261" },
  { name: "Mauritius", code: "MU", dialCode: "+230" },
  { name: "Seychelles", code: "SC", dialCode: "+248" },
  { name: "Comoros", code: "KM", dialCode: "+269" },
  { name: "Cape Verde", code: "CV", dialCode: "+238" },
  { name: "São Tomé and Príncipe", code: "ST", dialCode: "+239" },
  { name: "Equatorial Guinea", code: "GQ", dialCode: "+240" },
  { name: "Gabon", code: "GA", dialCode: "+241" },
  { name: "Republic of the Congo", code: "CG", dialCode: "+242" },
  { name: "Democratic Republic of the Congo", code: "CD", dialCode: "+243" },
  { name: "Central African Republic", code: "CF", dialCode: "+236" },
  { name: "Chad", code: "TD", dialCode: "+235" },
  { name: "Niger", code: "NE", dialCode: "+227" },
  { name: "Mali", code: "ML", dialCode: "+223" },
  { name: "Burkina Faso", code: "BF", dialCode: "+226" },
  { name: "Benin", code: "BJ", dialCode: "+229" },
  { name: "Togo", code: "TG", dialCode: "+228" },
  { name: "Liberia", code: "LR", dialCode: "+231" },
  { name: "Sierra Leone", code: "SL", dialCode: "+232" },
  { name: "Guinea", code: "GN", dialCode: "+224" },
  { name: "Guinea-Bissau", code: "GW", dialCode: "+245" },
  { name: "Gambia", code: "GM", dialCode: "+220" },
  { name: "Mauritania", code: "MR", dialCode: "+222" },
  { name: "Djibouti", code: "DJ", dialCode: "+253" },
  { name: "Eritrea", code: "ER", dialCode: "+291" },
  { name: "Somalia", code: "SO", dialCode: "+252" },
  { name: "Burundi", code: "BI", dialCode: "+257" },
  { name: "Rwanda", code: "RW", dialCode: "+250" },
  { name: "South Sudan", code: "SS", dialCode: "+211" },
  { name: "Réunion", code: "RE", dialCode: "+262" },
  { name: "Mayotte", code: "YT", dialCode: "+262" },
  { name: "French Guiana", code: "GF", dialCode: "+594" },
  { name: "French Polynesia", code: "PF", dialCode: "+689" },
  { name: "New Caledonia", code: "NC", dialCode: "+687" },
  { name: "Wallis and Futuna", code: "WF", dialCode: "+681" },
  { name: "American Samoa", code: "AS", dialCode: "+1" },
  { name: "Guam", code: "GU", dialCode: "+1" },
  { name: "Northern Mariana Islands", code: "MP", dialCode: "+1" },
  { name: "Puerto Rico", code: "PR", dialCode: "+1" },
  { name: "U.S. Virgin Islands", code: "VI", dialCode: "+1" },
  { name: "British Virgin Islands", code: "VG", dialCode: "+1" },
  { name: "Anguilla", code: "AI", dialCode: "+1" },
  { name: "Montserrat", code: "MS", dialCode: "+1" },
  { name: "Cayman Islands", code: "KY", dialCode: "+1" },
  { name: "Turks and Caicos Islands", code: "TC", dialCode: "+1" },
  { name: "Bermuda", code: "BM", dialCode: "+1" },
  { name: "Falkland Islands", code: "FK", dialCode: "+500" },
  {
    name: "South Georgia and the South Sandwich Islands",
    code: "GS",
    dialCode: "+500",
  },
  { name: "Saint Helena", code: "SH", dialCode: "+290" },
  { name: "Ascension Island", code: "AC", dialCode: "+247" },
  { name: "Tristan da Cunha", code: "TA", dialCode: "+290" },
  { name: "Saint Pierre and Miquelon", code: "PM", dialCode: "+508" },
  { name: "Greenland", code: "GL", dialCode: "+299" },
  { name: "Faroe Islands", code: "FO", dialCode: "+298" },
  { name: "Åland Islands", code: "AX", dialCode: "+358" },
  { name: "Svalbard and Jan Mayen", code: "SJ", dialCode: "+47" },
  { name: "Bouvet Island", code: "BV", dialCode: "+47" },
  { name: "Heard Island and McDonald Islands", code: "HM", dialCode: "+672" },
  { name: "Christmas Island", code: "CX", dialCode: "+61" },
  { name: "Cocos (Keeling) Islands", code: "CC", dialCode: "+61" },
  { name: "Norfolk Island", code: "NF", dialCode: "+672" },
  { name: "Pitcairn Islands", code: "PN", dialCode: "+64" },
  { name: "Tokelau", code: "TK", dialCode: "+690" },
  { name: "Niue", code: "NU", dialCode: "+683" },
  { name: "Cook Islands", code: "CK", dialCode: "+682" },
  { name: "Samoa", code: "WS", dialCode: "+685" },
  { name: "Tonga", code: "TO", dialCode: "+676" },
  { name: "Tuvalu", code: "TV", dialCode: "+688" },
  { name: "Kiribati", code: "KI", dialCode: "+686" },
  { name: "Nauru", code: "NR", dialCode: "+674" },
  { name: "Marshall Islands", code: "MH", dialCode: "+692" },
  { name: "Micronesia", code: "FM", dialCode: "+691" },
  { name: "Palau", code: "PW", dialCode: "+680" },
  { name: "Northern Cyprus", code: "TRNC", dialCode: "+90" },
  { name: "Kosovo", code: "XK", dialCode: "+383" },
  { name: "Western Sahara", code: "EH", dialCode: "+212" },
  { name: "Taiwan", code: "TW", dialCode: "+886" },
  { name: "Hong Kong", code: "HK", dialCode: "+852" },
  { name: "Macau", code: "MO", dialCode: "+853" },
  { name: "East Timor", code: "TL", dialCode: "+670" },
  { name: "Brunei", code: "BN", dialCode: "+673" },
  { name: "Cambodia", code: "KH", dialCode: "+855" },
  { name: "Laos", code: "LA", dialCode: "+856" },
  { name: "Myanmar", code: "MM", dialCode: "+95" },
  { name: "North Korea", code: "KP", dialCode: "+850" },
  { name: "Mongolia", code: "MN", dialCode: "+976" },
  { name: "Kazakhstan", code: "KZ", dialCode: "+7" },
  { name: "Kyrgyzstan", code: "KG", dialCode: "+996" },
  { name: "Tajikistan", code: "TJ", dialCode: "+992" },
  { name: "Turkmenistan", code: "TM", dialCode: "+993" },
  { name: "Uzbekistan", code: "UZ", dialCode: "+998" },
  { name: "Azerbaijan", code: "AZ", dialCode: "+994" },
  { name: "Georgia", code: "GE", dialCode: "+995" },
  { name: "Armenia", code: "AM", dialCode: "+374" },
  { name: "Moldova", code: "MD", dialCode: "+373" },
  { name: "Belarus", code: "BY", dialCode: "+375" },
  { name: "Ukraine", code: "UA", dialCode: "+380" },
  { name: "Romania", code: "RO", dialCode: "+40" },
  { name: "Bulgaria", code: "BG", dialCode: "+359" },
  { name: "Serbia", code: "RS", dialCode: "+381" },
  { name: "Croatia", code: "HR", dialCode: "+385" },
  { name: "Slovenia", code: "SI", dialCode: "+386" },
  { name: "Bosnia and Herzegovina", code: "BA", dialCode: "+387" },
  { name: "Montenegro", code: "ME", dialCode: "+382" },
  { name: "North Macedonia", code: "MK", dialCode: "+389" },
  { name: "Albania", code: "AL", dialCode: "+355" },
  { name: "Hungary", code: "HU", dialCode: "+36" },
  { name: "Slovakia", code: "SK", dialCode: "+421" },
  { name: "Czech Republic", code: "CZ", dialCode: "+420" },
  { name: "Estonia", code: "EE", dialCode: "+372" },
  { name: "Latvia", code: "LV", dialCode: "+371" },
  { name: "Lithuania", code: "LT", dialCode: "+370" },
  { name: "Iceland", code: "IS", dialCode: "+354" },
  { name: "Malta", code: "MT", dialCode: "+356" },
  { name: "Cyprus", code: "CY", dialCode: "+357" },
  { name: "Luxembourg", code: "LU", dialCode: "+352" },
  { name: "Liechtenstein", code: "LI", dialCode: "+423" },
  { name: "Monaco", code: "MC", dialCode: "+377" },
  { name: "San Marino", code: "SM", dialCode: "+378" },
  { name: "Vatican City", code: "VA", dialCode: "+379" },
  { name: "Andorra", code: "AD", dialCode: "+376" },
  { name: "Gibraltar", code: "GI", dialCode: "+350" },
  { name: "Isle of Man", code: "IM", dialCode: "+44" },
  { name: "Jersey", code: "JE", dialCode: "+44" },
  { name: "Guernsey", code: "GG", dialCode: "+44" },
];
